-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2022-04-15 20:28:46 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



ALTER TABLE Flight 
    DROP CONSTRAINT Flight_Aircraft_FK 
GO

DROP TABLE Aircraft
GO

ALTER TABLE Flight 
    DROP CONSTRAINT Flight_Airport_FK 
GO

ALTER TABLE Flight 
    DROP CONSTRAINT Flight_Airport_FKv2 
GO

ALTER TABLE Flight_history 
    DROP CONSTRAINT Flight_history_Airport_FK 
GO

ALTER TABLE Flight_history 
    DROP CONSTRAINT Flight_history_Airport_FKv2 
GO

ALTER TABLE Check_in 
    DROP CONSTRAINT Check_in_Airport_FK 
GO

DROP TABLE Airport
GO

ALTER TABLE Flight 
    DROP CONSTRAINT Flight_Employee_FK 
GO

ALTER TABLE Flight_Flight_attendant 
    DROP CONSTRAINT Flight_Flight_attendant_Employee_FK 
GO

ALTER TABLE Flight_Pilot 
    DROP CONSTRAINT Flight_Pilot_Employee_FK 
GO

DROP TABLE Employee
GO

ALTER TABLE Flight_Flight_attendant 
    DROP CONSTRAINT Flight_Flight_attendant_Flight_FK 
GO

ALTER TABLE Flight_history 
    DROP CONSTRAINT Flight_history_Flight_FK 
GO

ALTER TABLE Flight_Pilot 
    DROP CONSTRAINT Flight_Pilot_Flight_FK 
GO

ALTER TABLE Flight_ticket 
    DROP CONSTRAINT Flight_ticket_Flight_FK 
GO

DROP TABLE Flight
GO

DROP TABLE Flight_Flight_attendant
GO

DROP TABLE Flight_history
GO

DROP TABLE Flight_Pilot
GO

DROP TABLE Flight_ticket
GO

ALTER TABLE Check_in_Passenger 
    DROP CONSTRAINT Check_in_Passenger_Check_in_FK 
GO

DROP TABLE Check_in
GO

DROP TABLE Check_in_Passenger
GO

ALTER TABLE Aircraft 
    DROP CONSTRAINT Aircraft_Model_FK 
GO

DROP TABLE Model
GO

ALTER TABLE Flight_ticket 
    DROP CONSTRAINT Flight_ticket_Passenger_FK 
GO

ALTER TABLE Check_in_Passenger 
    DROP CONSTRAINT Check_in_Passenger_Passenger_FK 
GO

DROP TABLE Passenger
GO