-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2022-04-15 18:16:19 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Aircraft 
    (
     aircraft_id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     model_id INTEGER NOT NULL , 
     registration VARCHAR (10) NOT NULL , 
     flight_hours FLOAT NOT NULL ,
     deleted_date DATETIME
    )
GO

ALTER TABLE Aircraft ADD CONSTRAINT Aircraft_PK PRIMARY KEY CLUSTERED (aircraft_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Airport 
    (
     icao VARCHAR (4) NOT NULL , 
     name VARCHAR (100) NOT NULL , 
     city VARCHAR (50) NOT NULL , 
     country VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE Airport ADD CONSTRAINT Airport_PK PRIMARY KEY CLUSTERED (icao)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Employee 
    (
     employee_id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     role CHAR (1) NOT NULL , 
     first_name VARCHAR (50) NOT NULL , 
     last_name VARCHAR (50) NOT NULL , 
     birth_date DATE NOT NULL , 
     street VARCHAR (50) NOT NULL , 
     city VARCHAR (50) NOT NULL , 
     country VARCHAR (50) NOT NULL , 
     flight_hours FLOAT , 
     phone VARCHAR (15) NOT NULL , 
     email VARCHAR (100) 
    )
GO

ALTER TABLE Employee ADD CONSTRAINT Employee_PK PRIMARY KEY CLUSTERED (employee_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Flight 
    (
     flight_id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     aircraft_id INTEGER NOT NULL , 
     dispatcher_id INTEGER NOT NULL , 
     dpt_airport_icao VARCHAR (4) NOT NULL , 
     dst_airport_icao VARCHAR (4) NOT NULL , 
     dpt_time DATETIME NOT NULL , 
     dst_time DATETIME NOT NULL ,
     deleted_date DATETIME
    )
GO

ALTER TABLE Flight ADD CONSTRAINT Flight_PK PRIMARY KEY CLUSTERED (flight_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Flight_Flight_attendant 
    (
     flight_attendant_id INTEGER NOT NULL , 
     flight_id INTEGER NOT NULL 
    )
GO

ALTER TABLE Flight_Flight_attendant ADD CONSTRAINT Flight_Flight_attendant_PK PRIMARY KEY CLUSTERED (flight_attendant_id, flight_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Flight_history 
    (
     change_date DATETIME NOT NULL , 
     flight_id INTEGER NOT NULL , 
     dpt_airport_icao VARCHAR (4) NOT NULL , 
     dst_airport_icao VARCHAR (4) NOT NULL , 
     dpt_time DATETIME NOT NULL , 
     dst_time DATETIME NOT NULL , 
     deleted_date DATETIME 
    )
GO

ALTER TABLE Flight_history ADD CONSTRAINT Flight_history_PK PRIMARY KEY CLUSTERED (change_date)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Flight_Pilot 
    (
     pilot_id INTEGER NOT NULL , 
     flight_id INTEGER NOT NULL 
    )
GO

ALTER TABLE Flight_Pilot ADD CONSTRAINT Flight_Pilot_PK PRIMARY KEY CLUSTERED (pilot_id, flight_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Flight_ticket 
    (
     ticket_id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     passenger_id INTEGER NOT NULL , 
     flight_id INTEGER NOT NULL , 
     seat INTEGER NOT NULL , 
     deleted_date DATETIME 
    )
GO

ALTER TABLE Flight_ticket ADD CONSTRAINT Flight_ticket_PK PRIMARY KEY CLUSTERED (ticket_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Check_in 
    (
     check_in_id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     airport_icao VARCHAR (4) NOT NULL , 
     first_name VARCHAR (50) NOT NULL , 
     last_name VARCHAR (50) NOT NULL , 
     street VARCHAR (50) NOT NULL , 
     city VARCHAR (50) NOT NULL , 
     country VARCHAR (50) NOT NULL , 
     phone VARCHAR (15) NOT NULL , 
     email VARCHAR (50) 
    )
GO

ALTER TABLE Check_in ADD CONSTRAINT Check_in_PK PRIMARY KEY CLUSTERED (check_in_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Check_in_Passenger 
    (
     check_in_id INTEGER NOT NULL , 
     passenger_id INTEGER NOT NULL 
    )
GO

ALTER TABLE Check_in_Passenger ADD CONSTRAINT Check_in_Passenger_PK PRIMARY KEY CLUSTERED (check_in_id, passenger_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Model 
    (
     model_id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     manufacturer VARCHAR (50) NOT NULL , 
     name VARCHAR (20) NOT NULL , 
     max_passengers INTEGER NOT NULL , 
     max_speed INTEGER NOT NULL , 
     range INTEGER NOT NULL 
    )
GO

ALTER TABLE Model ADD CONSTRAINT Model_PK PRIMARY KEY CLUSTERED (model_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Passenger 
    (
     passenger_id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     first_name VARCHAR (50) NOT NULL , 
     last_name VARCHAR (50) NOT NULL , 
     street VARCHAR (50) NOT NULL , 
     city VARCHAR (50) NOT NULL , 
     country VARCHAR (50) NOT NULL , 
     phone VARCHAR (15) NOT NULL , 
     email VARCHAR (50) 
    )
GO

ALTER TABLE Passenger ADD CONSTRAINT Passenger_PK PRIMARY KEY CLUSTERED (passenger_id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Aircraft 
    ADD CONSTRAINT Aircraft_Model_FK FOREIGN KEY 
    ( 
     model_id
    ) 
    REFERENCES Model 
    ( 
     model_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight 
    ADD CONSTRAINT Flight_Aircraft_FK FOREIGN KEY 
    ( 
     aircraft_id
    ) 
    REFERENCES Aircraft 
    ( 
     aircraft_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight 
    ADD CONSTRAINT Flight_Airport_FK FOREIGN KEY 
    ( 
     dpt_airport_icao
    ) 
    REFERENCES Airport 
    ( 
     icao 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight 
    ADD CONSTRAINT Flight_Airport_FKv2 FOREIGN KEY 
    ( 
     dst_airport_icao
    ) 
    REFERENCES Airport 
    ( 
     icao 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight 
    ADD CONSTRAINT Flight_Employee_FK FOREIGN KEY 
    ( 
     dispatcher_id
    ) 
    REFERENCES Employee 
    ( 
     employee_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight_Flight_attendant 
    ADD CONSTRAINT Flight_Flight_attendant_Employee_FK FOREIGN KEY 
    ( 
     flight_attendant_id
    ) 
    REFERENCES Employee 
    ( 
     employee_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight_Flight_attendant 
    ADD CONSTRAINT Flight_Flight_attendant_Flight_FK FOREIGN KEY 
    ( 
     flight_id
    ) 
    REFERENCES Flight 
    ( 
     flight_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight_history 
    ADD CONSTRAINT Flight_history_Airport_FK FOREIGN KEY 
    ( 
     dpt_airport_icao
    ) 
    REFERENCES Airport 
    ( 
     icao 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight_history 
    ADD CONSTRAINT Flight_history_Airport_FKv2 FOREIGN KEY 
    ( 
     dst_airport_icao
    ) 
    REFERENCES Airport 
    ( 
     icao 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight_history 
    ADD CONSTRAINT Flight_history_Flight_FK FOREIGN KEY 
    ( 
     flight_id
    ) 
    REFERENCES Flight 
    ( 
     flight_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight_Pilot 
    ADD CONSTRAINT Flight_Pilot_Employee_FK FOREIGN KEY 
    ( 
     pilot_id
    ) 
    REFERENCES Employee 
    ( 
     employee_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight_Pilot 
    ADD CONSTRAINT Flight_Pilot_Flight_FK FOREIGN KEY 
    ( 
     flight_id
    ) 
    REFERENCES Flight 
    ( 
     flight_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight_ticket 
    ADD CONSTRAINT Flight_ticket_Flight_FK FOREIGN KEY 
    ( 
     flight_id
    ) 
    REFERENCES Flight 
    ( 
     flight_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Flight_ticket 
    ADD CONSTRAINT Flight_ticket_Passenger_FK FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES Passenger 
    ( 
     passenger_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Check_in 
    ADD CONSTRAINT Check_in_Airport_FK FOREIGN KEY 
    ( 
     airport_icao
    ) 
    REFERENCES Airport 
    ( 
     icao 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Check_in_Passenger 
    ADD CONSTRAINT Check_in_Passenger_Check_in_FK FOREIGN KEY 
    ( 
     check_in_id
    ) 
    REFERENCES Check_in 
    ( 
     check_in_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Check_in_Passenger 
    ADD CONSTRAINT Check_in_Passenger_Passenger_FK FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES Passenger 
    ( 
     passenger_id 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
